export const FETCH_REPO_START = 'FETCH_REPO_START'
export const FETCH_REPO_SUCCESS = 'FETCH_REPO_SUCCESS'
export const FETCH_REPO_FAILURE = 'FETCH_REPO_FAILURE'

export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const LOAD_MORE_REPO_START = 'LOAD_MORE_REPO_START'
export const LOAD_MORE_REPO_SUCCESS = 'LOAD_MORE_REPO_SUCCESS'
export const LOAD_MORE_REPO_FAILURE = 'LOAD_MORE_REPO_FAILURE'